#!/usr/libexec/platform-python
# EASY-INSTALL-ENTRY-SCRIPT: 'subscription-manager==1.27.18','console_scripts','rhsm-facts-service'
__requires__ = 'subscription-manager==1.27.18'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('subscription-manager==1.27.18', 'console_scripts', 'rhsm-facts-service')()
    )
